Update

diff --git a/include/functions b/include/functions
--- a/include/functions
+++ b/include/functions
@@ -2,14 +2,14 @@
 
 ################################################################################
 
-source /etc/pi-node/include/color
+source /etc/freedom-node/include/color
 
 ################################################################################
 
 # home directory
-HOME_DIR="$(cat /etc/pi-node/homedir 2>/dev/null)"
+HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"
 # user
-USER_NAME="$(cat /etc/pi-node/user 2>/dev/null)"
+USER_NAME="$(cat /etc/freedom-node/user 2>/dev/null)"
 
 ################################################################################
 # client commands
@@ -141,7 +141,7 @@ fi
 # repository version
 ################################################################################
 
-REPO_VERSION="${N0}v$(wc -l /etc/pi-node/*/* 2>/dev/null | grep "total" | egrep -o "[0-9]+" | sed 's/./&./g;s/\.$//')"
+REPO_VERSION="${N0}v$(wc -l /etc/freedom-node/*/* 2>/dev/null | grep "total" | egrep -o "[0-9]+" | sed 's/./&./g;s/\.$//')"
 
 ################################################################################
 # date
@@ -403,7 +403,7 @@ RANDOM_PUBLIC_IP=$((((RANDOM % 2) + 1)))
 
 # onion ip address
 if [[ "$RANDOM_PUBLIC_IP" == "1" ]] &>/dev/null; then
-  PUBLIC_IP="$(cat /etc/pi-node/hostname.onion 2>/dev/null)"
+  PUBLIC_IP="$(cat /etc/freedom-node/hostname.onion 2>/dev/null)"
   PUBLIC_IP="${P1}${PUBLIC_IP:0:9}...onion${N0:?}"
 fi
 # wan ip address
@@ -656,18 +656,18 @@ fi
 ################################################################################
 
 # create peers list
-grep "addr" /tmp/getpeerinfo.tmp 2>/dev/null | tr -d '",' | awk '{ print $2 }' | egrep "[0-9]+.[0-9]+.[0-9]+.[0-9]+" | egrep -v "[a-z]+" | awk -F: '{ print $1 }' >/etc/pi-node/peers
+grep "addr" /tmp/getpeerinfo.tmp 2>/dev/null | tr -d '",' | awk '{ print $2 }' | egrep "[0-9]+.[0-9]+.[0-9]+.[0-9]+" | egrep -v "[a-z]+" | awk -F: '{ print $1 }' >/etc/freedom-node/peers
 
 ################################################################################
 # arp list
 ################################################################################
 
 # if missing
-if [[ ! -f /etc/pi-node/arp ]] &>/dev/null; then
+if [[ ! -f /etc/freedom-node/arp ]] &>/dev/null; then
   # create arp list
-  cd /tmp || exit && sudo arp-scan "$(echo "$IP_ADDRESS" | egrep -o "[0-9]+.[0-9]+.[0-9]+").0"/24 >/etc/pi-node/arp
+  cd /tmp || exit && sudo arp-scan "$(echo "$IP_ADDRESS" | egrep -o "[0-9]+.[0-9]+.[0-9]+").0"/24 >/etc/freedom-node/arp
   # fetch ip address
-  echo "$(awk '{ print $1 }' /etc/pi-node/arp | egrep "[0-9]+.[0-9]+.[0-9]+.[0-9]+")" >/etc/pi-node/arp
+  echo "$(awk '{ print $1 }' /etc/freedom-node/arp | egrep "[0-9]+.[0-9]+.[0-9]+.[0-9]+")" >/etc/freedom-node/arp
   cd || exit
 fi
 
@@ -676,23 +676,23 @@ fi
 ################################################################################
 
 # if found
-if [[ -f /etc/pi-node/peers && -f /etc/pi-node/arp && -f "$HOME_DIR"/.trumpcoin/debug.log ]] &>/dev/null; then
+if [[ -f /etc/freedom-node/peers && -f /etc/freedom-node/arp && -f "$HOME_DIR"/.trumpcoin/debug.log ]] &>/dev/null; then
   # ip address peers
-  IP_ADDRESS_PEERS="$(cat /etc/pi-node/peers 2>/dev/null)"
+  IP_ADDRESS_PEERS="$(cat /etc/freedom-node/peers 2>/dev/null)"
   # ip address addnodes
-  IP_ADDRESS_ARP="$(cat /etc/pi-node/arp 2>/dev/null)"
+  IP_ADDRESS_ARP="$(cat /etc/freedom-node/arp 2>/dev/null)"
   # fetch failed connections
   IP_ADDRESS_FAILED="$(grep "(111)" "$HOME_DIR"/.trumpcoin/debug.log 2>/dev/null | awk '{ print $4 }' | awk -F: '{ print $1 }' | awk '!a[$0]++')"
   # if any data
   if [[ -n "$IP_ADDRESS_FAILED" ]] &>/dev/null; then
     # disregard already connected peers, create add list
-    echo "$(echo "$IP_ADDRESS_ARP" | grep -v "$IP_ADDRESS_PEERS" | grep -v "$IP_ADDRESS_FAILED")" >/etc/pi-node/add
+    echo "$(echo "$IP_ADDRESS_ARP" | grep -v "$IP_ADDRESS_PEERS" | grep -v "$IP_ADDRESS_FAILED")" >/etc/freedom-node/add
   else
     # disregard already connected peers, create add list
-    echo "$(echo "$IP_ADDRESS_ARP" | grep -v "$IP_ADDRESS_PEERS")" >/etc/pi-node/add
+    echo "$(echo "$IP_ADDRESS_ARP" | grep -v "$IP_ADDRESS_PEERS")" >/etc/freedom-node/add
   fi
   # fetch random address to add, duplicates removed
-  IP_ADDRESS_ADD="$(cat /etc/pi-node/add 2>/dev/null | awk '!a[$0]++' | sort -R | tail -1)"
+  IP_ADDRESS_ADD="$(cat /etc/freedom-node/add 2>/dev/null | awk '!a[$0]++' | sort -R | tail -1)"
   # if any numbers
   if [[ "$(echo "$IP_ADDRESS_ADD" | egrep -c "[0-9]+")" -eq "1" ]] &>/dev/null; then
     # add node
